# Deep Learning Exercise 1
## First week

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('Churn.csv')

### Step 1 : 
### Data exploration and preprocessing

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.shape

(10000, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [7]:
# checking the distribution of target labels
df.Exited.value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [8]:
# splitting in input and output space

# input space
X = df.iloc[:, 3:13].values
# output space
y = df.iloc[:, 13].values

In [9]:
# encoding categorical features
ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(drop="first"), [1,2])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
# defining Training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [11]:
# Standardization of the variables
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Step 2 :
### Modeling

In [12]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [13]:
# Creating an empty Neural Network
classifier = Sequential()

# adding the first layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
# adding the second layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
# adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

### Step 3 :
### Training process

In [14]:
# defining the optimizer, the loss function and the metric to use
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# fitting the training set
classifier.fit(X_train, y_train, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 579us/step - loss: 0.5658 - accuracy: 0.7945
Epoch 2/100
250/250 [==============================] - 0s 544us/step - loss: 0.4375 - accuracy: 0.7945
Epoch 3/100
250/250 [==============================] - 0s 541us/step - loss: 0.4317 - accuracy: 0.7945
Epoch 4/100
250/250 [==============================] - 0s 547us/step - loss: 0.4288 - accuracy: 0.7945
Epoch 5/100
250/250 [==============================] - 0s 535us/step - loss: 0.4260 - accuracy: 0.7945
Epoch 6/100
250/250 [==============================] - 0s 541us/step - loss: 0.4233 - accuracy: 0.7945
Epoch 7/100
250/250 [==============================] - 0s 537us/step - loss: 0.4208 - accuracy: 0.8123
Epoch 8/100
250/250 [==============================] - 0s 541us/step - loss: 0.4194 - accuracy: 0.8201
Epoch 9/100
250/250 [==============================] - 0s 538us/step - loss: 0.4182 - accuracy: 0.8232
Epoch 10/100
250/250 [==============================] - 0s 546us/step - loss: 0.4166 - accuracy: 0.8263
Epoch 11/100
250/250 [==============================] - 0s 539us/step - loss: 0.4158 - accuracy: 0.8286
Epoch 12/100
250/250 [==============================] - 0s 547us/step - loss: 0.4149 - accuracy: 0.8306
Epoch 13/100
250/250 [==============================] - 0s 539us/step - loss: 0.4141 - accuracy: 0.8313
Epoch 14/100
250/250 [==============================] - 0s 511us/step - loss: 0.4135 - accuracy: 0.8303
Epoch 15/100
250/250 [==============================] - 0s 511us/step - loss: 0.4128 - accuracy: 0.8322
Epoch 16/100
250/250 [==============================] - 0s 505us/step - loss: 0.4118 - accuracy: 0.8329
Epoch 17/100
250/250 [==============================] - 0s 567us/step - loss: 0.4112 - accuracy: 0.8320
Epoch 18/100
250/250 [==============================] - 0s 512us/step - loss: 0.4108 - accuracy: 0.8319
Epoch 19/100
250/250 [==============================] - 0s 485us/step - loss: 0.4103 - accuracy: 0.8332
Epoch 20/100
250/250 [==============================] - 0s 499us/step - loss: 0.4096 - accuracy: 0.8353
Epoch 21/100
250/250 [==============================] - 0s 453us/step - loss: 0.4094 - accuracy: 0.8340
Epoch 22/100
250/250 [==============================] - 0s 455us/step - loss: 0.4087 - accuracy: 0.8347
Epoch 23/100
250/250 [==============================] - 0s 456us/step - loss: 0.4083 - accuracy: 0.8347
Epoch 24/100
250/250 [==============================] - 0s 461us/step - loss: 0.4082 - accuracy: 0.8342
Epoch 25/100
250/250 [==============================] - 0s 458us/step - loss: 0.4079 - accuracy: 0.8338
Epoch 26/100
250/250 [==============================] - 0s 458us/step - loss: 0.4075 - accuracy: 0.8332
Epoch 27/100
250/250 [==============================] - 0s 460us/step - loss: 0.4069 - accuracy: 0.8342
Epoch 28/100
250/250 [==============================] - 0s 458us/step - loss: 0.4067 - accuracy: 0.8350
Epoch 29/100
250/250 [==============================] - 0s 473us/step - loss: 0.4067 - accuracy: 0.8344
Epoch 30/100
250/250 [==============================] - 0s 459us/step - loss: 0.4063 - accuracy: 0.8340
Epoch 31/100
250/250 [==============================] - 0s 451us/step - loss: 0.4061 - accuracy: 0.8339
Epoch 32/100
250/250 [==============================] - 0s 455us/step - loss: 0.4057 - accuracy: 0.8347
Epoch 33/100
250/250 [==============================] - 0s 455us/step - loss: 0.4056 - accuracy: 0.8356
Epoch 34/100
250/250 [==============================] - 0s 454us/step - loss: 0.4052 - accuracy: 0.8345
Epoch 35/100
250/250 [==============================] - 0s 469us/step - loss: 0.4053 - accuracy: 0.8349
Epoch 36/100
250/250 [==============================] - 0s 457us/step - loss: 0.4051 - accuracy: 0.8354
Epoch 37/100
250/250 [==============================] - 0s 459us/step - loss: 0.4049 - accuracy: 0.8354
Epoch 38/100
250/250 [==============================] - 0s 459us/step - loss: 0.4046 - accuracy: 0.8349
Epoch 39/100
250/250 [==============================] - 0s 511us/step - loss: 0.4042 - accuracy: 0.8355
Epoch 40/100
250/250 [==============================] - 0s 465us/step - loss: 0.4044 - accuracy: 0.8364
Epoch 41/100
250/250 [==============================] - 0s 464us/step - loss: 0.4040 - accuracy: 0.8354
Epoch 42/100
250/250 [==============================] - 0s 465us/step - loss: 0.4038 - accuracy: 0.8356
Epoch 43/100
250/250 [==============================] - 0s 463us/step - loss: 0.4039 - accuracy: 0.8363
Epoch 44/100
250/250 [==============================] - 0s 463us/step - loss: 0.4040 - accuracy: 0.8359
Epoch 45/100
250/250 [==============================] - 0s 462us/step - loss: 0.4035 - accuracy: 0.8357
Epoch 46/100
250/250 [==============================] - 0s 466us/step - loss: 0.4036 - accuracy: 0.8351
Epoch 47/100
250/250 [==============================] - 0s 475us/step - loss: 0.4035 - accuracy: 0.8342
Epoch 48/100
250/250 [==============================] - 0s 459us/step - loss: 0.4034 - accuracy: 0.8357
Epoch 49/100
250/250 [==============================] - 0s 467us/step - loss: 0.4030 - accuracy: 0.8353
Epoch 50/100
250/250 [==============================] - 0s 455us/step - loss: 0.4029 - accuracy: 0.8351
Epoch 51/100
250/250 [==============================] - 0s 467us/step - loss: 0.4032 - accuracy: 0.8351
Epoch 52/100
250/250 [==============================] - 0s 465us/step - loss: 0.4029 - accuracy: 0.8356
Epoch 53/100
250/250 [==============================] - 0s 467us/step - loss: 0.4028 - accuracy: 0.8360
Epoch 54/100
250/250 [==============================] - 0s 465us/step - loss: 0.4025 - accuracy: 0.8354
Epoch 55/100
250/250 [==============================] - 0s 481us/step - loss: 0.4023 - accuracy: 0.8357
Epoch 56/100
250/250 [==============================] - 0s 459us/step - loss: 0.4021 - accuracy: 0.8370
Epoch 57/100
250/250 [==============================] - 0s 459us/step - loss: 0.4022 - accuracy: 0.8353
Epoch 58/100
250/250 [==============================] - 0s 451us/step - loss: 0.4020 - accuracy: 0.8354
Epoch 59/100
250/250 [==============================] - 0s 463us/step - loss: 0.4026 - accuracy: 0.8356
Epoch 60/100
250/250 [==============================] - 0s 451us/step - loss: 0.4020 - accuracy: 0.8354
Epoch 61/100
250/250 [==============================] - 0s 451us/step - loss: 0.4015 - accuracy: 0.8360
Epoch 62/100
250/250 [==============================] - 0s 467us/step - loss: 0.4017 - accuracy: 0.8355
Epoch 63/100
250/250 [==============================] - 0s 450us/step - loss: 0.4015 - accuracy: 0.8360
Epoch 64/100
250/250 [==============================] - 0s 475us/step - loss: 0.4015 - accuracy: 0.8349
Epoch 65/100
250/250 [==============================] - 0s 463us/step - loss: 0.4017 - accuracy: 0.8355
Epoch 66/100
250/250 [==============================] - 0s 459us/step - loss: 0.4018 - accuracy: 0.8345
Epoch 67/100
250/250 [==============================] - 0s 467us/step - loss: 0.4014 - accuracy: 0.8344
Epoch 68/100
250/250 [==============================] - 0s 454us/step - loss: 0.4013 - accuracy: 0.8353
Epoch 69/100
250/250 [==============================] - 0s 473us/step - loss: 0.4015 - accuracy: 0.8350
Epoch 70/100
250/250 [==============================] - 0s 483us/step - loss: 0.4010 - accuracy: 0.8359
Epoch 71/100
250/250 [==============================] - 0s 471us/step - loss: 0.4014 - accuracy: 0.8347
Epoch 72/100
250/250 [==============================] - 0s 451us/step - loss: 0.4012 - accuracy: 0.8341
Epoch 73/100
250/250 [==============================] - 0s 462us/step - loss: 0.4012 - accuracy: 0.8354
Epoch 74/100
250/250 [==============================] - 0s 455us/step - loss: 0.4011 - accuracy: 0.8351
Epoch 75/100
250/250 [==============================] - 0s 479us/step - loss: 0.4011 - accuracy: 0.8353
Epoch 76/100
250/250 [==============================] - 0s 469us/step - loss: 0.4012 - accuracy: 0.8344
Epoch 77/100
250/250 [==============================] - 0s 467us/step - loss: 0.4010 - accuracy: 0.8353
Epoch 78/100
250/250 [==============================] - 0s 455us/step - loss: 0.4011 - accuracy: 0.8340
Epoch 79/100

250/250 [==============================] - 0s 467us/step - loss: 0.4009 - accuracy: 0.8356
Epoch 80/100
250/250 [==============================] - 0s 455us/step - loss: 0.4010 - accuracy: 0.8350
Epoch 81/100
250/250 [==============================] - 0s 470us/step - loss: 0.4008 - accuracy: 0.8345
Epoch 82/100
250/250 [==============================] - 0s 471us/step - loss: 0.4007 - accuracy: 0.8340
Epoch 83/100
250/250 [==============================] - 0s 649us/step - loss: 0.4008 - accuracy: 0.8344
Epoch 84/100
250/250 [==============================] - 0s 543us/step - loss: 0.4005 - accuracy: 0.8345
Epoch 85/100
250/250 [==============================] - 0s 546us/step - loss: 0.4009 - accuracy: 0.8353
Epoch 86/100
250/250 [==============================] - 0s 501us/step - loss: 0.4005 - accuracy: 0.8341
Epoch 87/100
250/250 [==============================] - 0s 454us/step - loss: 0.4006 - accuracy: 0.8367
Epoch 88/100
250/250 [==============================] - 0s 451us/step - loss: 0.4003 - accuracy: 0.8350
Epoch 89/100
250/250 [==============================] - 0s 455us/step - loss: 0.4005 - accuracy: 0.8354
Epoch 90/100
250/250 [==============================] - 0s 459us/step - loss: 0.4006 - accuracy: 0.8359
Epoch 91/100
250/250 [==============================] - 0s 463us/step - loss: 0.4003 - accuracy: 0.8341
Epoch 92/100
250/250 [==============================] - 0s 479us/step - loss: 0.4005 - accuracy: 0.8353
Epoch 93/100
250/250 [==============================] - 0s 490us/step - loss: 0.4005 - accuracy: 0.8351
Epoch 94/100
250/250 [==============================] - 0s 522us/step - loss: 0.4005 - accuracy: 0.8349
Epoch 95/100
250/250 [==============================] - 0s 518us/step - loss: 0.4006 - accuracy: 0.8360
Epoch 96/100
250/250 [==============================] - 0s 462us/step - loss: 0.4004 - accuracy: 0.8354
Epoch 97/100
250/250 [==============================] - 0s 463us/step - loss: 0.4004 - accuracy: 0.8346
Epoch 98/100
250/250 [==============================] - 0s 451us/step - loss: 0.4004 - accuracy: 0.8347
Epoch 99/100
250/250 [==============================] - 0s 451us/step - loss: 0.3999 - accuracy: 0.8360
Epoch 100/100
250/250 [==============================] - 0s 455us/step - loss: 0.3999 - accuracy: 0.8345

### Step 4 :
### Evaluation

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
# displaying the predictionof the target label
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [16]:
# Creating the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
# dispaying the confusion matrix
cm

array([[1556,   51],
       [ 263,  130]], dtype=int64)

In [17]:
# Print Statistics from Confusion Matrix
target_names = ['Stay', 'Leave']
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

        Stay       0.86      0.97      0.91      1607
       Leave       0.72      0.33      0.45       393

    accuracy                           0.84      2000
   macro avg       0.79      0.65      0.68      2000
weighted avg       0.83      0.84      0.82      2000